tea:
  url: shop/tea/
  price: 10
  weight: "114"
  size: small
  vars: "small|medium[+3]|large[+6]"

lipbalm:
  url: shop/skincare/
  price: 8
  weight: "10.58"
  ingredients:
    - avocado oil
    - jojoba oil
    - beeswax
  vars: "unflavored | spearmint | peppermint | tea tree | orange | grapefruit"
  pricing: "small | large[+2]"

lotion:
  url: shop/skincare/
  price: 15
  weight: 216.93
  ingredients:
    - water
    - wax
    - vitamin e
    - natural perservatives

tinctures:
  url: shop/tinctures/
  price: 12
  ingredients: 
    - alcohol
  vars: "1 oz | 2oz | 4oz | 8oz"


