tea:
  url: shop/tea/
  price: 10
  weight: 114

lipbalm:
  url: shop/skincare/
  price: 8
  weight: 11
  height: 7
  width: 2
  length: 2
  ingredients:
    - avocado oil
    - jojoba oil
    - beeswax
  vars: "unflavored | spearmint | peppermint | tea tree | orange | grapefruit"

lotion:
  url: shop/skincare/
  price: 15
  weight: 217
  ingredients:
    - water
    - wax
    - vitamin e
    - natural perservatives

tinctures:
  url: shop/tinctures/
  price: 15
  ingredients: 
    - alcohol

notebooks:
  url: shop/notebooks
  price: 15
notebooksdl:
  url: shop/notebooks
  price: 10
