tea:
  url: shop/tea/
  price: 10
  weight: "114"

lipbalm:
  url: shop/skincare/
  price: 8
  weight: "10.58"
  ingredients:
    - avocado oil
    - jojoba oil
    - beeswax
  vars: "unflavored | spearmint | peppermint | tea tree | orange | grapefruit"

lotion:
  url: shop/skincare/
  price: 15
  weight: 216.93
  ingredients:
    - water
    - wax
    - vitamin e
    - natural perservatives

tinctures:
  url: shop/tinctures/
  price: 15
  ingredients: 
    - alcohol

notebooks:
  url: shop/notebooks
  price: 15
notebooks-downloads:
  url: shop/notebooks
  price: 10
